include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_print: true
    use_key_in_widget_constructors: true

analyzer:
  errors:
    prefer_const_constructors: info
    deprecated_member_use: info
  exclude:
    - build/**
    - web/**
